url: https://beardy.digital

# Site settings
title: Beardy Digital
email: craig@beardy.digital
description: "Beardy Digital is a software consultancy, specialising in all aspects of software enginnering, from cloud migration, software engineering through to security and dev ops."


# Team names, titles and social links
people:
- name: Craig Godden-Payne
  image: img/craig.png
  position: Principal Software Engineer
  social:
    - title: twitter
      url: https://twitter.com/DigitalBeardy
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Lucy Godden-Payne
  image: img/lucy.png
  position: Company Secretary
  social:
    - title: twitter
      url: https://twitter.com/DigitalBeardy
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Unfilled Position
  position: Technology Specialist
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Unfilled Position
  position: Research Specialist
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Unfilled Position
  position: Marketing Specialist
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/digitalbeardy
  - title: facebook
    url: 
  - title: github
    url: 

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-sitemap
